---
apiVersion: k8s.troven.io/v1alpha1
kind: APIService
metadata:
  name: api-service-example
spec:
  paths:
    /proxy/healthz:
      get:
        summary: Health check via proxy
        feature:
          operationId: api.proxy
          target: http://localhost:5008/healthz
        responses:
         '200':
            description: "200 response"
            content:
              application/json: {}

    /proxy/secure_healthz:
      get:
        summary: Health check via proxy
        feature:
          operationId: api.proxy
          target: http://localhost:5008/healthz
        security:
          - oauth2_jwt: [ "controller:api:healthz" ]
        responses:
         '200':
            description: "200 response"
            content:
              application/json: {}

    /proxy/healthz_secure:
      get:
        summary: Health check via proxy
        feature:
          operationId: api.proxy
          target: http://localhost:5008/secure_healthz
        responses:
         '200':
            description: "200 response"
            content:
              application/json: {}

