---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wardens.k8s.troven.io
spec:
  group: k8s.troven.io
  version: v1alpha1
  names:
    kind: Warden
    listKind: WardenList
    plural: wardens
    singular: warden
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
          - paths
          properties:
            paths:
              type: object
              additionalProperties: true
              # patternProperties:
              #   '^(get|put|post|delete|options|head|patch|trace)$':
              #     $ref: '#/definitions/Operation'
              #   '^x-': {}
              # properties:
              #   type: object
              #   properties:
              #     claims:
              #       type: object
              #     target:
              #       type: object
