---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iapis.k8s.troven.co
spec:
  group: k8s.troven.co
  version: v1alpha1
  names:
    kind: IAPI
    listKind: IAPIList
    plural: iapis
    singular: iapi
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          additionalProperties: true
          required:
          - paths
          properties:
            paths:
              type: object
              additionalProperties: true
              # patternProperties:
              #   '^(get|put|post|delete|options|head|patch|trace)$':
              #     $ref: '#/definitions/Operation'
              #   '^x-': {}
              # properties:
              #   type: object
              #   properties:
              #     claims:
              #       type: object
              #     target:
              #       type: object
