name: api-service-warden
port: 5008
host: example.demo.troven.co

auditor:
  enabled: true
  file:
    filename: apis-chassis.audit.log

logging:
  enabled: true
  file:
    filename: apis-chassis.log

features:

  json:
    enabled: true

  warden:
    enabled: true

