name: api-service-controller
port: 5008
host: controller.demo.troven.co

auditor:
  enabled: true
  File:
    filename: apis-controller.audit.log

logging:
  enabled: true
  File:
    filename: apis-controller.log

features:
  json:
    enabled: true

  prometheus:
    enabled: true

  openapi:
    enabled: true

  iapi:
    enabled: true
    namespace: tenant-example

openapi:
  servers:
    - url: https://api.example.k8s.net.au/
  info:
    title: Controller OpenAPI
  paths:

    /healthz:
      get:
        summary: Health check
        chassis:
          operationId: api.heartbeat
        responses:
         '200':
            description: "200 response"
            content:
              application/json: {}

    /secure_healthz:
      get:
        summary: Health check
        feature:
          operationId: api.heartbeat
        security:
          - oauth2_jwt: [ "example:api:healthz" ]
        responses:
         '200':
            description: "200 response"
            content:
              application/json: {}

    /swagger:
      get:
        summary: Open API docs
        feature:
          operationId: api.apidocs
        responses:
         '200':
            description: "200 response"
            content:
              application/json: {}

  components:
    securitySchemes:
      oauth2_jwt:
        type: http
        scheme: bearer
        description: JWT bearer key to authorize requests.
        bearerFormat: JWT
        name: authorization
        in: header
