name: api-service-controller
port: 5008
host: controller.demo.troven.co

auditor:
  enabled: true
  File:
    filename: api-controller.audit.log

logging:
  enabled: true
  File:
    filename: api-controller.log

features:
  payload:

  prometheus:
    enabled: true

  jwt:
    secret: false
    claims:
      jti: "1234"

  pipeline:
    before:
      api.gregarious:
        headers:
          X-BEFORE: true
    after:

  openapi:
    enabled: true
    before:
      api.gregarious:
        headers:
          X-BEFORE: true
    after:
      api.gregarious:
        headers:
          X-AFTER: true

  controller:
    enabled: true
    crd: false
    folder: "./k8s/"


openapi:
  servers:
    - url: https://api.example.k8s.net.au/
  info:
    title: Controller OpenAPI
  paths:
    # /:
    #   all:
    #     feature:
    #       before:
    #         gregarious:
    #           headers:
    #             X-FEATURE: true

    /healthz:
      get:
        summary: Health check
        feature:
          before:
            # api.gregarious:
            #   headers:
            #     X-HEALTHZ-BEFORE: true
          after:
          featureId: api.heartbeat
        responses:
         '200':
            description: "200 response"
            content:
              application/json: {}

    /swagger:
      get:
        summary: Open API docs
        feature:
          featureId: api.apidocs
        responses:
         '200':
            description: "200 response"
            content:
              application/json: {}

  components:
    securitySchemes:
      oauth2_jwt:
        type: http
        scheme: bearer
        description: JWT bearer key to authorize requests.
        bearerFormat: JWT
        name: authorization
        in: header
