name: api-service-controller
port: 5008

auditor:
  enabled: true
  File:
    filename: api-controller.audit.log

logging:
  enabled: true
  Console:
    enabled: true

features:
  logging:

  payload:
    enabled: true

  cors:
    enabled: true

  prometheus:
    enabled: true

  jwt:
    secret: false
    claims:

  pipeline:
    before:
    after:

  openapi:
    enabled: true
    before:
    after:

  controller:
    enabled: true
    crd: false
    folder: "./k8s/"

  mongodb:
    host: localhost
    port: 27017
    database: example
    ssl: false

openapi:
  servers:
    - url: https://api.example.a6s.dev/
  info:
    title: Controller OpenAPI

  paths:
    /:
      get:
        summary: Open API docs
        feature:
          apidocs:
            enable: true
        responses:
         '200':
            description: "200 response"
            content:
              application/json: {}

    /healthz:
      get:
        summary: Health check
        feature:
          heartbeat:
            enabled: true
        responses:
         '200':
            description: "200 response"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/healthz"

    /health:
      get:
        summary: Health check
        feature:
          heartbeat:
            enabled: true
        responses:
         '200':
            description: "200 response"
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    ok:
                      type: string

  components:
    schemas:
      healthz:
        type: object
        properties:
          ok:
            type: string
    securitySchemes:
      oauth2_jwt:
        type: http
        scheme: bearer
        description: JWT bearer key to authorize requests.
        bearerFormat: JWT
