name: api-service-controller
port: 5008

auditor:
  enabled: true
  File:
    filename: api-controller.audit.log

logging:
  enabled: true
  File:
    filename: api-controller.log
  Console:
    enabled: true

features:

  payload:

  prometheus:
    enabled: true

  jwt:
    secret: false
    claims:

  pipeline:
    before:
    after:

  openapi:
    enabled: true
    before:
    after:

  controller:
    enabled: true
    crd: true
    folder: "./k8s/"


openapi:
  servers:
    - url: https://api.example.a6s.dev/
  info:
    title: Controller OpenAPI
  paths:
    /healthz:
      get:
        summary: Health check
        feature:
          heartbeat:
            enabled: true
        responses:
         '200':
            description: "200 response"
            content:
              application/json: {}

    /swagger:
      get:
        summary: Open API docs
        feature:
          apidocs:
            enable: true
        responses:
         '200':
            description: "200 response"
            content:
              application/json: {}

  components:
    securitySchemes:
      oauth2_jwt:
        type: http
        scheme: bearer
        description: JWT bearer key to authorize requests.
        bearerFormat: JWT
        name: authorization
        in: header
