---
apiVersion: k8s.a6s.dev/v1
kind: OpenAPI
metadata:
  name: api-service-apis
  labels:
    controller: "api-service-controller"
spec:
  paths:
    /apis/example:
      get:
        summary: APIs example
        feature:
          apis:
            healthz:
              url: "/healthz"
        responses:
          '200':
            description: "200 response"
            content:
              application/json: {}

  components:
    schemas:
