---
apiVersion: k8s.a6s.dev/v1
kind: OpenAPI
metadata:
    name: api-service-proxy
    labels:
        controller: "api-service-controller"
spec:
    paths:
        # /proxy/healthz:
        #     get:
        #         feature:
        #             proxy:
        #                 target: "http://localhost:5008/healthz"
        #                 ignorePath: false
        #                 prependPath: false
        # /proxy/models/{type}/:
        #     get:
        #         parameters:
        #             - in: path
        #               name: type
        #               schema:
        #                   type: string
        #               required: true
        #               description: type of proxy
        #         feature:
        #             proxy:
        #                 target: "http://localhost:5008/models/{{path.type}}/"
        #                 enabled: true
        #     post:
        #         parameters:
        #             - in: path
        #               name: type
        #               schema:
        #                   type: string
        #               required: true
        #               description: type of proxy
        #         feature:
        #             proxy:
        #                 target: "http://localhost:5008/models/{{path.type}}/"
        #                 enabled: true
